FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY . ./
RUN dotnet restore .\Microservice
RUN dotnet publish  .\Microservice\Gateway\Gateway.csproj -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/Microservice/Gateway/out .
ENTRYPOINT ["dotnet", "Gateway.dll"]